# Generated by Django 5.0.3 on 2024-04-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_sku',
            field=models.CharField(default='sin SKU', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
