# Generated by Django 5.0.3 on 2024-04-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_remove_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
